### PR TITLE
Support for Swagger/OpenAPI definition files

### PR DESCRIPTION
**Pull request by nilshedstrom**
Added support for generating API operations and schemas as swagger/openapi definitions instead of arm templates. If you set SeparateSwaggerFile=true for  Write-APIManagementTemplates it will generate Swagger/OpenAPI definitions as separate files.

I think this possibility is good because users can update the swagger definition file when there is a change in the backend and then deploy the new files to API Management. 

Also
- Added support vor virtualnetwork configuration

- Added default values for Get-APIManagementTemplate as separate column

- Added unit tests for ListAPIInProduct

- Fixed bug in Azure where subscriptionRequired always was generated even though you need apiversion 20180601preview to deploy an API with that property

### CODE REVIEW

**Comment by Geronius** [comment]
Hi @nilshedstrom, when I use SeparateSwaggerFile $true I get a error within Dev-Ops (see below). Did you test this yourself?

`{
	"code": "DeploymentFailed",
	"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
	"details": [{
			"code": "BadRequest",
			"message": "{\r\n \"error\": {\r\n \"code\": \"InvalidTemplate\",\r\n \"message\": \"Deployment template parse failed: 'Could not find member 'swagger' on object of type 'Template'. Path 'swagger', line 2, position 12.'.\"\r\n }\r\n}"
		}, {
			"code": "BadRequest",
			"message": "{\r\n \"error\": {\r\n \"code\": \"InvalidTemplate\",\r\n \"message\": \"Deployment template parse failed: 'Could not find member 'swagger' on object of type 'Template'. Path 'swagger', line 2, position 12.'.\"\r\n }\r\n}"
		}
	]
}
`

**Comment by nilshedstrom** [comment]
@Geronius Yes. I have deployed my arm templates and they work.
Can you tell me what parameters you used when generating the templates?
And possibly the contents (or part of it) of the arm-template that fails.

I use the following parameters
armclient token 80d4fe69-xxxx-4dd2-a938-9250f1c8ab03 | Get-APIManagementTemplate -APIManagement MyApiManagementInstance -ResourceGroup myResourceGroup -SubscriptionId 80d4fe69-xxxx-4dd2-a938-9250f1c8ab03 -ParametrizePropertiesOnly $true -FixedServiceNameParameter $true -CreateApplicationInsightsInstance $true -ReplaceSetBackendServiceBaseUrlWithProperty $true -ExportSwaggerDefinition $true | Write-APIManagementTemplates -OutputDirectory C:\temp\templates -ApiStandalone $true -SeparatePolicyFile $true -SeparateSwaggerFile $true -MergeTemplates $true -GenerateParameterFiles $true -ReplaceListSecretsWithParameter $true -ListApiInProduct $false

**Comment by Geronius** [comment]
@nilshedstrom Maybe I know why this happend. It was a wsdl import and this was not a valid swaggerFile. I disabled the SeparateSwaggerFile option and still there was a error. 

But i'm not sure thats the reason. My param are like below:
armclient token $subscriptionid | Get-APIManagementTemplate -FixedServiceNameParameter $true -APIFilters $filter -APIManagement $apimanagementname -ResourceGroup $resourcegroupname -SubscriptionId $subscriptionid -TenantName $tenant -ExportPIManagementInstance $false -ExportProducts $false -ExportAuthorizationServers $false -ExportGroups $false -ReplaceSetBackendServiceBaseUrlWithProperty $true -ExportTags $true -ExportSwaggerDefinition $true -ParametrizePropertiesOnly $true | Write-APIManagementTemplates -GenerateParameterFiles $false -DebugTemplateFile $filenname -OutputDirectory $outputFolder -SeparatePolicyFile $true -ApiStandalone $false -SeparateSwaggerFile $true

**Comment by nilshedstrom** [comment]
@Geronius 
-ExportSwaggerDefinition will put the (invalid?) swagger definition into your arm template. So you will probably not be able to deploy it (with SeparateSwaggerFile as $true or $false).

Using ExportSwaggerDefinition=$true and SeparateSwaggerFile =$false is not supported due to limitations in Azure (this is mentioned in README.md).
I tested importing wsdl-files and I could generate arm templates (with swagger definitions) and deploy them.
I was not able to get into a state where I had an invalid swagger definition in the API Management Instance.
I tried deploying an invalid swagger files but I did not get the same error message as you did.

If the swagger definition is invalid in the source API Management instance or someone edits the file so it becomes invalid I think it is reasonable that the arm deploy should fail.

Are you suggesting that we validate the swagger definition before putting it into the arm template(s)?

**Pull request merged**
