### PR TITLE
Some small changes made.

### PR DESCRIPTION
**Pull request by Geronius**
- Sometime old endpoint are not cleaned-up, this will result in null. So skip these resources

- Removed referenceApplicationInsightsInstrumentationKey from condition becauce this setting derives from CreateApplicationInsightsInstance the link to a ApplicationInsights also is added to the api's if this settings is false.

### CODE REVIEW

**Comment by nilshedstrom** [comment]
The if-statement you modified 
```c#
if (applicationInsightsLogger && referenceApplicationInsightsInstrumentationKey)
```
is related to the following code in DeploymentTemplate->CreateLogger
```c#
if (referenceApplicationInsightsInstrumentationKey && loggerType == "applicationInsights" && credentials.Value<string>("instrumentationKey") != null)
{
    string parameter = AddParameter($"{GetServiceName(serviceName, false)}_applicationInsights", "string", loggerName);
    credentials["instrumentationKey"] = $"[reference(resourceId('Microsoft.Insights/components', parameters('{parameter}')), '2014-04-01').InstrumentationKey]";
    ...
}
```
So the modified name for the application insights logger resource is only needed if CreateApplicationInsightsInstance is $true.
After your modification the modified name is used for application insights loggers even when CreateApplicationInsightsInstance is $false.
The downside to this is that the modified name does not consider parametrizePropertiesOnly and users will get more parameters than needed. 

When searching for _applicationInsights I only find it used when CreateApplicationInsightsInstance  is $true so I dont understand why your modified if-statement is needed when CreateApplicationInsightsInstance  is $false

**Comment by Geronius** [comment]
> The if-statement you modified
> 
> ```cs
> if (applicationInsightsLogger && referenceApplicationInsightsInstrumentationKey)
> ```
> 
> is related to the following code in DeploymentTemplate->CreateLogger
> 
> ```cs
> if (referenceApplicationInsightsInstrumentationKey && loggerType == "applicationInsights" && credentials.Value<string>("instrumentationKey") != null)
> {
>     string parameter = AddParameter($"{GetServiceName(serviceName, false)}_applicationInsights", "string", loggerName);
>     credentials["instrumentationKey"] = $"[reference(resourceId('Microsoft.Insights/components', parameters('{parameter}')), '2014-04-01').InstrumentationKey]";
>     ...
> }
> ```
> 
> So the modified name for the application insights logger resource is only needed if CreateApplicationInsightsInstance is $true.
> After your modification the modified name is used for application insights loggers even when CreateApplicationInsightsInstance is $false.
> The downside to this is that the modified name does not consider parametrizePropertiesOnly and users will get more parameters than needed.
> 
> When searching for _applicationInsights I only find it used when CreateApplicationInsightsInstance is $true so I dont understand why your modified if-statement is needed when CreateApplicationInsightsInstance is $false

The is a new method: CreateApiDiagnostic. This one adds the connection to the logger within the API if there is one. It does not create the DiagnosticLogger.

**Comment by nilshedstrom** [comment]
Ok. Then I dont have any issues with this.

**Comment by Geronius** [comment]
Hi @MLogdberg, can you please merge this PR?

**Comment by MLogdberg** [comment]
Yes, sorry for the slack.

**Pull request merged**
