### PR TITLE
List api names

### PR DESCRIPTION
**Pull request by Geronius**
Hi Mattias,

I have created a feature what will add api's as list in the product. Its much cleaner and easier to add an API in a product. I use the arm-copy method to let this work.

Let me no if you like it.

Result looks like this:
{
	"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
		"apimServiceName": {
			"type": "string",
			"defaultValue": "zzl-test"
		},
		"product_powerbrowser_name": {
			"type": "string",
			"defaultValue": "powerbrowser"
		},
		**"apis_in_product_powerbrowser": {
			"type": "array",
			"defaultValue": [
				"StUFDCRDocumentcreatie",
				"StUFZKNZS-DMS"
			]
		}**
	},
	"variables": {},
	"resources": [{
			"comments": "Generated for resource /subscriptions/8a8643af-8580-451d-8373-e58af2781896/resourceGroups/apim-test-rg/providers/Microsoft.ApiManagement/service/zzl-test/products/powerbrowser",
			"type": "Microsoft.ApiManagement/service/products",
			"name": "[concat(parameters('apimServiceName'), '/' ,parameters('product_powerbrowser_name'))]",
			"apiVersion": "2017-03-01",
			"properties": {
				"displayName": "PowerBrowser",
				"description": "Alle API's welke door PowerBrowser direct kunnen worden aangeroepen.",
				"terms": null,
				"subscriptionRequired": false,
				"approvalRequired": null,
				"subscriptionsLimit": null,
				"state": "notPublished"
			},
			"resources": [],
			"dependsOn": []
		}, **{
			"name": "[concat(parameters('apimServiceName'), '/' ,parameters('product_powerbrowser_name'), '/', parameters('apis_in_product_powerbrowser')[copyIndex()])]",
			"type": "Microsoft.ApiManagement/service/products/apis",
			"tags": {
				"displayName": "ListOfApis"
			},
			"apiVersion": "2017-03-01",
			"dependsOn": [
				"[resourceId('Microsoft.ApiManagement/service/products', parameters('apimServiceName'), '/' ,parameters('product_powerbrowser_name'))]"
			],
			"copy": {
				"name": "apicopy",
				"count": "[length(parameters('apis_in_product_powerbrowser'))]"
			}
		}**
	]
}

### CODE REVIEW

**Comment by MLogdberg** [comment]
Sounds good, just a question do you know if this will append or rewrite the connected API's to a Product?

**Comment by Geronius** [comment]
It removes the existing APIs from the product resource. Then it removes the parameters that are not in use anymore.

**Comment by Geronius** [comment]
I created a branch for this so you can check it out first.

**Comment by MLogdberg** [comment]
Sounds good I'll look in to as soon as I can, but proboly will be after christmas since all pre christmas stuffs need to be done now :)

**Comment by nilshedstrom** [comment]
The parameter ListApiInProduct was introduced and set to true as default. 
I ran into some problems because of this because suddenly I got some strange behavior when I use ApiStandalone=true.

I think this parameter (including default value) should be documented in the README.md. 
I also suggest that the default value should be changed to false and then the users (that read the documentation) can decide if they want to use ListApiInProduct or ApiStandalone
@Geronius  @MLogdberg

**Comment by MLogdberg** [comment]
Hi,

Totaly agree, we need to change the default value and document. My bad for not finding this before approving.

Med vänlig hälsning,
Mattias

Skickat från min iPhone

6 mars 2019 kl. 17:50 skrev Nils Hedström <notifications@github.com<mailto:notifications@github.com>>:


The parameter ListApiInProduct was introduced and set to true as default.
I ran into some problems because of this because suddenly I got some strange behavior when I use ApiStandalone=true.

I think this parameter (including default value) should be documented in the README.md.
I also suggest that the default value should be changed to false and then the users (that read the documentation) can decide if they want to use ListApiInProduct or ApiStandalone
@Geronius<https://github.com/Geronius> @MLogdberg<https://github.com/MLogdberg>

**Comment by Geronius** [comment]
Hello,

Of course you are right. It's better to make this optional. 

Regards
Gert

**Comment by nilshedstrom** [comment]
When adding unit tests for this functionallity I realized that the current implementation only works when ParametrizePropertiesOnly=false
This should also be included in the documentation. 

It is possible to add support for this functionallity when ParametrizePropertiesOnly=true and ApiStandalone=true

**Comment by Geronius** [comment]
I will update the readme and make the default false.

I will try to implement the ParametrizePropertiesOnly=true

**Comment by nilshedstrom** [comment]
Great. The unit tests I made are available in this commit. 
https://github.com/MLogdberg/APIManagementARMTemplateCreator/commit/cff49ab71a62ee8361c0b611886497770822c00a

When you want to write tests for ParameterizePropertiesOnly=true you need to switch to a different input template. 
Change the line 21 to
   _sourceTemplate = Utils.GetEmbededFileContent("APIManagementTemplate.Test.SamplesTemplate.template.json");

**Comment by Geronius** [comment]
> Great. The unit tests I made are available in this commit.
> [cff49ab](https://github.com/MLogdberg/APIManagementARMTemplateCreator/commit/cff49ab71a62ee8361c0b611886497770822c00a)
> 
> When you want to write tests for ParameterizePropertiesOnly=true you need to switch to a different input template.
> Change the line 21 to
> _sourceTemplate = Utils.GetEmbededFileContent("APIManagementTemplate.Test.SamplesTemplate.template.json");

I made the changes and added to the pull request. When your PR is accepted I will make the unit test work. Thanks for al the work you put into the UnitTest already!

**Pull request merged**
