### PR TITLE
Certificate and Diagnostics

### PR DESCRIPTION
**Pull request by Geronius**
Now you can decide to export the certificates or not. Default is still true.

Added a resource to the api so diagnostics attached to the api is exported to. This is the example:

`{
	"comments": "Generated for resource /subscriptions/..../resourceGroups/..../providers/Microsoft.ApiManagement/service/....-dev-westeu/apis/..../diagnostics/....",
	"type": "Microsoft.ApiManagement/service/apis/diagnostics",
	"name": "[concat(parameters('apimServiceName'), '/', parameters('api_...._name'), '/', parameters('logger_....-dev_name'))]",
	"apiVersion": "2018-06-01-preview",
	"properties": {
		"alwaysLog": "[parameters('diagnostic_...._alwaysLog')]",
		"enableHttpCorrelationHeaders": "[parameters('diagnostic_...._enableHttpCorrelationHeaders')]",
		"logClientIp": true,
		"loggerId": "[resourceId('Microsoft.ApiManagement/service/loggers', parameters('apimServiceName'), parameters('logger_....-dev_name'))]",
		"sampling": {
			"samplingType": "fixed",
			"percentage": "[parameters('diagnostic_...._samplingPercentage')]"
		},
		"frontend": {
			"request": {
				"headers": [],
				"body": {
					"bytes": 1024
				}
			},
			"response": {
				"headers": [],
				"body": {
					"bytes": 1024
				}
			}
		},
		"backend": {
			"request": {
				"headers": [],
				"body": {
					"bytes": 0
				}
			},
			"response": {
				"headers": [],
				"body": {
					"bytes": 0
				}
			}
		}
	},
	"resources": [],
	"dependsOn": []
}`

### CODE REVIEW

**Comment by Geronius** [comment]
Added bugfix Property SubscriptionRequired not supported before 208-06-01-preview.…

**Comment by MLogdberg** [comment]
There is a lot of errors in the tests, can you please fix them? of 173 tests 71 failed. (guessing it's the version?)

**Comment by Geronius** [comment]
Hello Mattias,

The tests were ook till the last merge😔. I already am trying to fix them. It has something to do with the example files and the diagnostics. I merge again when the problems are solved. 

Kind regards


Verstuurd vanaf mijn iPhone

**Comment by Geronius** [comment]
I updated a lot of stuf. The are Ok this time :-). Also updated readme and ListApiInProduct.

**Comment by Geronius** [comment]
I made some changes after merge #52 and #51 because there where merge errors. Now the build is okay and the tests are valid. I hope this PR is now ready to accept.

@nilshedstrom I updated the unit test you created, there where some minor issues with the test values. Thanks again for preparing this tests!

**Comment by MLogdberg** [comment]
Looks good, sorry for making some extra work due to the merge of #52.
Just one question, should we have export certificates default value to true?

**Comment by Geronius** [comment]
> Looks good, sorry for making some extra work due to the merge of #52.
> Just one question, should we have export certificates default value to true?

I think so, it is the default before this param was introduced.

**Comment by MLogdberg** [comment]
Feels a bit scary in my opinion, could we set it to false as default so we don't introduce a breaking change?

**Comment by Geronius** [comment]
Fine by me. But the default was that the certs were exported. So default false in my eyes is a breaking change.

**Comment by MLogdberg** [comment]
Okey then we go for true as default. Thanks!

**Pull request merged**
